### ISSUE TITLE
Tollbar position

### ISSUE THREAD

**Issue by andrebrandao-dev** [gnans/PDFViewer#1]
![image](https://user-images.githubusercontent.com/1919433/89811432-0dc48300-db15-11ea-973f-1397272f5ba5.png)

how can i change the toolbar position ?

**Comment by WuglyakBolgoink** [comment]
@gnans  can u please fix this?

**Comment by WuglyakBolgoink** [comment]
@andrebrandaoo do you have any other ideas how to open internal pdf files?

**Comment by gnans** [comment]
> @gnans can u please fix this?

This issue is fixed in **1.0.9**
