### ISSUE TITLE
Preview of PDF is not fullscreen

### ISSUE THREAD

**Issue by HanzChen** [gnans/PDFViewer#2]
Hi There,

Really thanks for this plugin, which is excellent and easy to use.
However, recently I find out that the preview layout is not fullscreen anymore.

Here is my options:
```javascript
var PDFViewerOptions = {
    fileName: "Document.pdf",
    doneBtnText: "Done",
    showShareBtn: "true",
    printBtnText: "Print",
    doneBtnColour: "#0A7AFF",
    printBtnColour: "#0A7AFF",
    shareBtnColour: "#0A7AFF",
    shareBtnText: "Share",
}
```
Cordova: 10.0.0
Cordova-ios: 6.2.0
Plugin version: 1.0.9

![image](https://user-images.githubusercontent.com/59546710/130222516-8cc31888-aca7-4ee3-a03d-2ef6485bb30f.png)

Issue happends in IOS 13/14/15, and no matter of which iPad device.

**Comment by gnans** [comment]
Hi @HanzChen,

Thanks for the support. Are you looking for a full screen option like hiding the status bar as well ?

**Comment by HanzChen** [comment]
> Hi @HanzChen,
> 
> Thanks for the support. Are you looking for a full screen option like hiding the status bar as well ?

Hi, Yes! A full screen option, hiding status bar!
Thanks you!

**Comment by gnans** [comment]
Hi @HanzChen,

Please check the previous version of this plugin 1.0.8

**Comment by HanzChen** [comment]
> Hi @HanzChen,
> 
> Please check the previous version of this plugin 1.0.8

Hi, I take a long holiday these few days.
1.0.8 have no such issue while 1.0.9 have.

Thanks
